# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_server_main.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ServerMain(object):
    def setupUi(self, ServerMain):
        ServerMain.setObjectName("ServerMain")
        ServerMain.resize(271, 600)
        self.centralwidget = QtWidgets.QWidget(ServerMain)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 251, 561))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 30, 241, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ui_StartServer = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.ui_StartServer.setObjectName("ui_StartServer")
        self.horizontalLayout.addWidget(self.ui_StartServer)
        self.ui_StopServer = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.ui_StopServer.setObjectName("ui_StopServer")
        self.horizontalLayout.addWidget(self.ui_StopServer)
        self.horizontalLayoutWidget.raise_()
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 30, 241, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ui_ArchivesOpen = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.ui_ArchivesOpen.setObjectName("ui_ArchivesOpen")
        self.horizontalLayout_2.addWidget(self.ui_ArchivesOpen)
        self.horizontalLayoutWidget_2.raise_()
        self.groupBox.raise_()
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_4 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_4)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(0, 30, 241, 51))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ui_TemplatesUpdate = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.ui_TemplatesUpdate.setObjectName("ui_TemplatesUpdate")
        self.horizontalLayout_4.addWidget(self.ui_TemplatesUpdate)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.groupBox_3 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_3)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(0, 30, 241, 51))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ui_GraphicsOpen = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.ui_GraphicsOpen.setObjectName("ui_GraphicsOpen")
        self.horizontalLayout_3.addWidget(self.ui_GraphicsOpen)
        self.horizontalLayoutWidget_3.raise_()
        self.groupBox.raise_()
        self.groupBox.raise_()
        self.verticalLayout.addWidget(self.groupBox_3)
        self.verticalLayoutWidget.raise_()
        self.groupBox_3.raise_()
        ServerMain.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ServerMain)
        self.statusbar.setObjectName("statusbar")
        ServerMain.setStatusBar(self.statusbar)

        self.retranslateUi(ServerMain)
        QtCore.QMetaObject.connectSlotsByName(ServerMain)

    def retranslateUi(self, ServerMain):
        _translate = QtCore.QCoreApplication.translate
        ServerMain.setWindowTitle(_translate("ServerMain", "Администрирование"))
        self.groupBox.setTitle(_translate("ServerMain", "Работа с сервером"))
        self.ui_StartServer.setText(_translate("ServerMain", "Запуск"))
        self.ui_StopServer.setText(_translate("ServerMain", "Остановка"))
        self.groupBox_2.setTitle(_translate("ServerMain", "Работа с резервными копиями"))
        self.ui_ArchivesOpen.setText(_translate("ServerMain", "Открыть утилиту"))
        self.groupBox_4.setTitle(_translate("ServerMain", "Работа со шаблонами (фото)"))
        self.ui_TemplatesUpdate.setText(_translate("ServerMain", "Обновить после загрузки"))
        self.groupBox_3.setTitle(_translate("ServerMain", "Работа со статистикой"))
        self.ui_GraphicsOpen.setText(_translate("ServerMain", "Открыть утилиту"))

