# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_design.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.resize(987, 643)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setAnimated(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.uielem_startSearch = QtWidgets.QPushButton(self.centralwidget)
        self.uielem_startSearch.setEnabled(False)
        self.uielem_startSearch.setGeometry(QtCore.QRect(10, 580, 111, 31))
        self.uielem_startSearch.setObjectName("uielem_startSearch")
        self.uielem_progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.uielem_progressBar.setGeometry(QtCore.QRect(130, 580, 841, 31))
        self.uielem_progressBar.setProperty("value", 0)
        self.uielem_progressBar.setObjectName("uielem_progressBar")
        self.ui_hairTypeComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.ui_hairTypeComboBox.setGeometry(QtCore.QRect(230, 10, 231, 41))
        self.ui_hairTypeComboBox.setObjectName("ui_hairTypeComboBox")
        self.ui_hairTypeComboBox.addItem("")
        self.ui_hairTypeComboBox.addItem("")
        self.ui_hairTypeComboBox.addItem("")
        self.ui_hairTypeComboBox.addItem("")
        self.ui_hairTypeLabel = QtWidgets.QLabel(self.centralwidget)
        self.ui_hairTypeLabel.setGeometry(QtCore.QRect(10, 20, 201, 16))
        self.ui_hairTypeLabel.setObjectName("ui_hairTypeLabel")
        self.ui_hairTypeDescriptionTable = QtWidgets.QTableWidget(self.centralwidget)
        self.ui_hairTypeDescriptionTable.setGeometry(QtCore.QRect(10, 140, 961, 431))
        self.ui_hairTypeDescriptionTable.setFrameShape(QtWidgets.QFrame.Box)
        self.ui_hairTypeDescriptionTable.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.ui_hairTypeDescriptionTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.ui_hairTypeDescriptionTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.ui_hairTypeDescriptionTable.setTabKeyNavigation(False)
        self.ui_hairTypeDescriptionTable.setProperty("showDropIndicator", False)
        self.ui_hairTypeDescriptionTable.setDragDropOverwriteMode(False)
        self.ui_hairTypeDescriptionTable.setAlternatingRowColors(True)
        self.ui_hairTypeDescriptionTable.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.ui_hairTypeDescriptionTable.setTextElideMode(QtCore.Qt.ElideRight)
        self.ui_hairTypeDescriptionTable.setShowGrid(True)
        self.ui_hairTypeDescriptionTable.setGridStyle(QtCore.Qt.SolidLine)
        self.ui_hairTypeDescriptionTable.setWordWrap(True)
        self.ui_hairTypeDescriptionTable.setCornerButtonEnabled(False)
        self.ui_hairTypeDescriptionTable.setObjectName("ui_hairTypeDescriptionTable")
        self.ui_hairTypeDescriptionTable.setColumnCount(4)
        self.ui_hairTypeDescriptionTable.setRowCount(7)
        item = QtWidgets.QTableWidgetItem()
        self.ui_hairTypeDescriptionTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ui_hairTypeDescriptionTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.ui_hairTypeDescriptionTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.ui_hairTypeDescriptionTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.ui_hairTypeDescriptionTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.ui_hairTypeDescriptionTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.ui_hairTypeDescriptionTable.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.ui_hairTypeDescriptionTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ui_hairTypeDescriptionTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.ui_hairTypeDescriptionTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.ui_hairTypeDescriptionTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.ui_hairTypeDescriptionTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ui_hairTypeDescriptionTable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.ui_hairTypeDescriptionTable.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.ui_hairTypeDescriptionTable.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.ui_hairTypeDescriptionTable.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ui_hairTypeDescriptionTable.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.ui_hairTypeDescriptionTable.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.ui_hairTypeDescriptionTable.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.ui_hairTypeDescriptionTable.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ui_hairTypeDescriptionTable.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.ui_hairTypeDescriptionTable.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.ui_hairTypeDescriptionTable.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.ui_hairTypeDescriptionTable.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ui_hairTypeDescriptionTable.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.ui_hairTypeDescriptionTable.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.ui_hairTypeDescriptionTable.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.ui_hairTypeDescriptionTable.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ui_hairTypeDescriptionTable.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.ui_hairTypeDescriptionTable.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.ui_hairTypeDescriptionTable.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.ui_hairTypeDescriptionTable.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ui_hairTypeDescriptionTable.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.ui_hairTypeDescriptionTable.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.ui_hairTypeDescriptionTable.setItem(5, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.ui_hairTypeDescriptionTable.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ui_hairTypeDescriptionTable.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.ui_hairTypeDescriptionTable.setItem(6, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.ui_hairTypeDescriptionTable.setItem(6, 3, item)
        self.ui_hairTypeDescriptionTable.horizontalHeader().setCascadingSectionResizes(False)
        self.ui_hairTypeDescriptionTable.horizontalHeader().setHighlightSections(False)
        self.ui_hairTypeDescriptionTable.verticalHeader().setVisible(True)
        self.ui_hairTypeDescriptionTable.verticalHeader().setCascadingSectionResizes(False)
        self.ui_hairTypeDescriptionTable.verticalHeader().setDefaultSectionSize(30)
        self.ui_hairTypeDescriptionTable.verticalHeader().setHighlightSections(False)
        self.ui_hairColorLabel = QtWidgets.QLabel(self.centralwidget)
        self.ui_hairColorLabel.setGeometry(QtCore.QRect(510, 20, 201, 16))
        self.ui_hairColorLabel.setObjectName("ui_hairColorLabel")
        self.ui_hairColorComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.ui_hairColorComboBox.setGeometry(QtCore.QRect(730, 10, 231, 41))
        self.ui_hairColorComboBox.setObjectName("ui_hairColorComboBox")
        self.ui_hairColorComboBox.addItem("")
        self.ui_hairColorComboBox.addItem("")
        self.ui_hairColorComboBox.addItem("")
        self.ui_hairColorComboBox.addItem("")
        self.ui_hairColorComboBox.addItem("")
        self.ui_hairColorComboBox.addItem("")
        self.ui_hairColorComboBox.addItem("")
        self.ui_hairColorComboBox.addItem("")
        self.ui_hairColorComboBox.addItem("")
        self.ui_hairColorComboBox.addItem("")
        self.ui_hairColorComboBox.addItem("")
        self.ui_hairColorComboBox.addItem("")
        self.ui_hairColorComboBox.addItem("")
        self.ui_hairColorComboBox.addItem("")
        self.ui_hairColorComboBox.addItem("")
        self.ui_hairColorComboBox.addItem("")
        self.ui_hairLengthComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.ui_hairLengthComboBox.setGeometry(QtCore.QRect(230, 60, 231, 41))
        self.ui_hairLengthComboBox.setObjectName("ui_hairLengthComboBox")
        self.ui_hairLengthComboBox.addItem("")
        self.ui_hairLengthComboBox.addItem("")
        self.ui_hairLengthComboBox.addItem("")
        self.ui_hairLengthLabel = QtWidgets.QLabel(self.centralwidget)
        self.ui_hairLengthLabel.setGeometry(QtCore.QRect(10, 70, 201, 21))
        self.ui_hairLengthLabel.setObjectName("ui_hairLengthLabel")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(730, 70, 112, 23))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(850, 70, 112, 23))
        self.radioButton_2.setCheckable(True)
        self.radioButton_2.setChecked(False)
        self.radioButton_2.setObjectName("radioButton_2")
        self.ui_hairColorLabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.ui_hairColorLabel_2.setGeometry(QtCore.QRect(510, 70, 201, 16))
        self.ui_hairColorLabel_2.setObjectName("ui_hairColorLabel_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Система подбора причесок"))
        self.uielem_startSearch.setText(_translate("MainWindow", "Поиск"))
        self.ui_hairTypeComboBox.setItemText(0, _translate("MainWindow", "Нормальные"))
        self.ui_hairTypeComboBox.setItemText(1, _translate("MainWindow", "Жирные"))
        self.ui_hairTypeComboBox.setItemText(2, _translate("MainWindow", "Сухие"))
        self.ui_hairTypeComboBox.setItemText(3, _translate("MainWindow", "Смешанные"))
        self.ui_hairTypeLabel.setText(_translate("MainWindow", "Выберите свой тип волос:"))
        self.ui_hairTypeDescriptionTable.setSortingEnabled(False)
        item = self.ui_hairTypeDescriptionTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Потребность в мытье"))
        item = self.ui_hairTypeDescriptionTable.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Кожа головы, корни волос"))
        item = self.ui_hairTypeDescriptionTable.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Кончики (при средней длине волос)"))
        item = self.ui_hairTypeDescriptionTable.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Блеск"))
        item = self.ui_hairTypeDescriptionTable.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Пышность и объем"))
        item = self.ui_hairTypeDescriptionTable.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "Электризация"))
        item = self.ui_hairTypeDescriptionTable.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "Укладка без стайлинговых средств"))
        item = self.ui_hairTypeDescriptionTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Нормальные"))
        item = self.ui_hairTypeDescriptionTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Жирные"))
        item = self.ui_hairTypeDescriptionTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Сухие"))
        item = self.ui_hairTypeDescriptionTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Смешанные"))
        __sortingEnabled = self.ui_hairTypeDescriptionTable.isSortingEnabled()
        self.ui_hairTypeDescriptionTable.setSortingEnabled(False)
        item = self.ui_hairTypeDescriptionTable.item(0, 0)
        item.setText(_translate("MainWindow", "Каждые  2 – 3 дня"))
        item = self.ui_hairTypeDescriptionTable.item(0, 1)
        item.setText(_translate("MainWindow", "Ежедневно"))
        item = self.ui_hairTypeDescriptionTable.item(0, 2)
        item.setText(_translate("MainWindow", "Один раз в неделю"))
        item = self.ui_hairTypeDescriptionTable.item(0, 3)
        item.setText(_translate("MainWindow", "Каждые  2 – 4 дня"))
        item = self.ui_hairTypeDescriptionTable.item(1, 0)
        item.setText(_translate("MainWindow", "После мытья нормальные,\n"
"через пару дней  жирные"))
        item = self.ui_hairTypeDescriptionTable.item(1, 1)
        item.setText(_translate("MainWindow", "После мытья нормальные, вечером первого дня или утром второго снова жирные"))
        item = self.ui_hairTypeDescriptionTable.item(1, 2)
        item.setText(_translate("MainWindow", "После мытья – сухие или нормальные, 3-4 дня нормальные, к 7-му дню — жирные"))
        item = self.ui_hairTypeDescriptionTable.item(1, 3)
        item.setText(_translate("MainWindow", "После мытья нормальные, через 2-3 дня  жирные"))
        item = self.ui_hairTypeDescriptionTable.item(2, 0)
        item.setText(_translate("MainWindow", "Нормальные или чуть сухие, могут немного сечься кончики"))
        item = self.ui_hairTypeDescriptionTable.item(2, 1)
        item.setText(_translate("MainWindow", "Не секутся или почти не секутся"))
        item = self.ui_hairTypeDescriptionTable.item(2, 2)
        item.setText(_translate("MainWindow", "Сухие, ломкие, может быть много обломанных или секущихся кончиков"))
        item = self.ui_hairTypeDescriptionTable.item(2, 3)
        item.setText(_translate("MainWindow", "Сухие, секутся"))
        item = self.ui_hairTypeDescriptionTable.item(3, 0)
        item.setText(_translate("MainWindow", "После мытья – чистый блеск,  через 2-3 дня – жирный блеск у корней"))
        item = self.ui_hairTypeDescriptionTable.item(3, 1)
        item.setText(_translate("MainWindow", "Чистый блеск после мытья, жирный блеск к концу первого дня или утру второго"))
        item = self.ui_hairTypeDescriptionTable.item(3, 2)
        item.setText(_translate("MainWindow", "После мытья – легкий блеск, затем волосы тускнеют"))
        item = self.ui_hairTypeDescriptionTable.item(3, 3)
        item.setText(_translate("MainWindow", "После мытья  чистый блеск у корней, небольшой блеск – на кончиках. На 3-4 день – жирный блеск у корней и отсутствие блеска на кончиках"))
        item = self.ui_hairTypeDescriptionTable.item(4, 0)
        item.setText(_translate("MainWindow", "Нормальная пышность"))
        item = self.ui_hairTypeDescriptionTable.item(4, 1)
        item.setText(_translate("MainWindow", "Только сразу после мытья или совсем нет"))
        item = self.ui_hairTypeDescriptionTable.item(4, 2)
        item.setText(_translate("MainWindow", "Усиленная"))
        item = self.ui_hairTypeDescriptionTable.item(4, 3)
        item.setText(_translate("MainWindow", "Средняя, могут пушиться кончики"))
        item = self.ui_hairTypeDescriptionTable.item(5, 0)
        item.setText(_translate("MainWindow", "Иногда"))
        item = self.ui_hairTypeDescriptionTable.item(5, 1)
        item.setText(_translate("MainWindow", "Очень редко"))
        item = self.ui_hairTypeDescriptionTable.item(5, 2)
        item.setText(_translate("MainWindow", "Часто"))
        item = self.ui_hairTypeDescriptionTable.item(5, 3)
        item.setText(_translate("MainWindow", "Может быть на кончиках"))
        item = self.ui_hairTypeDescriptionTable.item(6, 0)
        item.setText(_translate("MainWindow", "Поддаются хорошо"))
        item = self.ui_hairTypeDescriptionTable.item(6, 1)
        item.setText(_translate("MainWindow", "Волосы поддаются укладке, но она держится недолго"))
        item = self.ui_hairTypeDescriptionTable.item(6, 2)
        item.setText(_translate("MainWindow", "Плохо поддаются укладке"))
        item = self.ui_hairTypeDescriptionTable.item(6, 3)
        item.setText(_translate("MainWindow", "Прикорневая укладка"))
        self.ui_hairTypeDescriptionTable.setSortingEnabled(__sortingEnabled)
        self.ui_hairColorLabel.setText(_translate("MainWindow", "Выберите цвет волос:"))
        self.ui_hairColorComboBox.setItemText(0, _translate("MainWindow", "Красный"))
        self.ui_hairColorComboBox.setItemText(1, _translate("MainWindow", "Красно-оранжевый"))
        self.ui_hairColorComboBox.setItemText(2, _translate("MainWindow", "Розово-красный"))
        self.ui_hairColorComboBox.setItemText(3, _translate("MainWindow", "Розовый"))
        self.ui_hairColorComboBox.setItemText(4, _translate("MainWindow", "Пурпурно-розовый"))
        self.ui_hairColorComboBox.setItemText(5, _translate("MainWindow", "Пурпурный"))
        self.ui_hairColorComboBox.setItemText(6, _translate("MainWindow", "Сине-фиолетовый"))
        self.ui_hairColorComboBox.setItemText(7, _translate("MainWindow", "Синий"))
        self.ui_hairColorComboBox.setItemText(8, _translate("MainWindow", "Циан-синий"))
        self.ui_hairColorComboBox.setItemText(9, _translate("MainWindow", "Циан"))
        self.ui_hairColorComboBox.setItemText(10, _translate("MainWindow", "Зеленый-циан"))
        self.ui_hairColorComboBox.setItemText(11, _translate("MainWindow", "Зеленый"))
        self.ui_hairColorComboBox.setItemText(12, _translate("MainWindow", "Желто-зеленый"))
        self.ui_hairColorComboBox.setItemText(13, _translate("MainWindow", "Желтый"))
        self.ui_hairColorComboBox.setItemText(14, _translate("MainWindow", "Оранжево-желтый"))
        self.ui_hairColorComboBox.setItemText(15, _translate("MainWindow", "Оранжево-коричневый"))
        self.ui_hairLengthComboBox.setItemText(0, _translate("MainWindow", "Короткие"))
        self.ui_hairLengthComboBox.setItemText(1, _translate("MainWindow", "Средние"))
        self.ui_hairLengthComboBox.setItemText(2, _translate("MainWindow", "Длинные"))
        self.ui_hairLengthLabel.setText(_translate("MainWindow", "Выберите длину волос:"))
        self.radioButton.setText(_translate("MainWindow", "Мужчина"))
        self.radioButton_2.setText(_translate("MainWindow", "Женщина"))
        self.ui_hairColorLabel_2.setText(_translate("MainWindow", "Выберите ваш пол:"))

